alias gh='git hist -n20'
alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias sed='gsed'
alias ls='lsd'
alias ll='lsd -lah'
alias tree='lsd --tree'
alias pod='arch -arm64 pod'

